"""phase2 connector creds documents sync_runs cursor

Revision ID: d5a8a1f072a2
Revises: 670ba8188df1
Create Date: 2026-06-08 17:54:32.249009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd5a8a1f072a2'
down_revision: Union[str, None] = '670ba8188df1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connector_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('connector_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('access_token_enc', sa.LargeBinary(), nullable=False),
    sa.Column('refresh_token_enc', sa.LargeBinary(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scope', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'connector_id', name='uq_creds_workspace_connector')
    )
    op.create_index(op.f('ix_connector_credentials_connector_id'), 'connector_credentials', ['connector_id'], unique=False)
    op.create_index(op.f('ix_connector_credentials_workspace_id'), 'connector_credentials', ['workspace_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('connector_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'provider', 'external_id', name='uq_documents_ws_provider_external')
    )
    op.create_index(op.f('ix_documents_connector_id'), 'documents', ['connector_id'], unique=False)
    op.create_index(op.f('ix_documents_workspace_id'), 'documents', ['workspace_id'], unique=False)
    op.create_table('sync_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('connector_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('docs_seen', sa.Integer(), nullable=False),
    sa.Column('docs_ingested', sa.Integer(), nullable=False),
    sa.Column('chunks_written', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('cursor', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_runs_connector_id'), 'sync_runs', ['connector_id'], unique=False)
    op.create_index(op.f('ix_sync_runs_workspace_id'), 'sync_runs', ['workspace_id'], unique=False)
    op.add_column('connectors', sa.Column('last_cursor', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connectors', 'last_cursor')
    op.drop_index(op.f('ix_sync_runs_workspace_id'), table_name='sync_runs')
    op.drop_index(op.f('ix_sync_runs_connector_id'), table_name='sync_runs')
    op.drop_table('sync_runs')
    op.drop_index(op.f('ix_documents_workspace_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_connector_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_connector_credentials_workspace_id'), table_name='connector_credentials')
    op.drop_index(op.f('ix_connector_credentials_connector_id'), table_name='connector_credentials')
    op.drop_table('connector_credentials')
    # ### end Alembic commands ###
